// Mock data for skincare e-commerce admin
window.MOCK = {
  kpis: {
    products: { value: 248, delta: 4.2, sub: "12 new this week" },
    orders: { value: 1842, delta: 12.5, sub: "vs last month" },
    revenue: { value: "$94,328", delta: 18.3, sub: "vs last month" },
    customers: { value: 7321, delta: 6.8, sub: "289 new" },
    reviews: { value: 3492, delta: 9.1, sub: "4.8 avg rating" },
    lowStock: { value: 14, delta: -2.1, sub: "items need restock" },
    subscribers: { value: 12480, delta: 5.6, sub: "newsletter" },
    promos: { value: 23, delta: 0, sub: "active codes" },
  },
  sales30d: [4200,4800,5100,4700,5400,6100,5800,5200,5900,6700,6400,7100,7400,6800,7900,8200,7600,8400,9100,8700,9300,9800,9200,10100,10800,10300,11200,11800,11400,12100],
  ordersBy: [120,140,135,160,180,210,195,220,245,260,290,310],
  customers12m: [2100,2400,2750,3100,3450,3900,4400,4900,5400,6100,6700,7321],
  channelMix: [54, 22, 14, 10],
  funnel: [12480, 6420, 3210, 1842, 1610],
  cohorts: [
    [100, 62, 48, 41, 36, 33, 31],
    [100, 58, 44, 39, 34, 30],
    [100, 64, 51, 44, 38],
    [100, 60, 47, 42],
    [100, 65, 52],
    [100, 68],
  ],
  topProducts: [
    { name: "Hydra-Glow Serum", brand: "Lumière", price: 64, sold: 1284, growth: 22, emoji: "💧" },
    { name: "Velvet Cream Moisturizer", brand: "Aurora", price: 52, sold: 1102, growth: 18, emoji: "🌸" },
    { name: "Vitamin C Brightening Mask", brand: "Lumière", price: 38, sold: 980, growth: 14, emoji: "🍋" },
    { name: "Niacinamide 10% Booster", brand: "Pure Lab", price: 28, sold: 874, growth: 9, emoji: "🧪" },
    { name: "Retinol Night Repair", brand: "Aurora", price: 72, sold: 712, growth: -4, emoji: "🌙" },
  ],
  recentOrders: [
    { id: "#1284", customer: "Sofia Martínez", email: "sofia@mail.com", total: 184.20, status: "paid", items: 3, date: "Today, 2:14 PM" },
    { id: "#1283", customer: "Liam Chen", email: "liam@mail.com", total: 62.00, status: "processing", items: 1, date: "Today, 1:02 PM" },
    { id: "#1282", customer: "Amelia Brown", email: "ami@mail.com", total: 248.75, status: "paid", items: 4, date: "Today, 11:48 AM" },
    { id: "#1281", customer: "Noah Patel", email: "noah@mail.com", total: 38.00, status: "pending", items: 1, date: "Today, 10:33 AM" },
    { id: "#1280", customer: "Hana Yoshida", email: "hana@mail.com", total: 412.50, status: "shipped", items: 6, date: "Yesterday" },
    { id: "#1279", customer: "Olivia Ross", email: "liv@mail.com", total: 96.00, status: "delivered", items: 2, date: "Yesterday" },
    { id: "#1278", customer: "Mateo Silva", email: "mateo@mail.com", total: 128.40, status: "refunded", items: 2, date: "Yesterday" },
  ],
  recentReviews: [
    { product: "Hydra-Glow Serum", user: "Sofia M.", stars: 5, text: "Absolutely glowing skin after 2 weeks. The texture is silky and absorbs instantly." },
    { product: "Velvet Cream", user: "Amelia B.", stars: 5, text: "My dry skin finally feels balanced. Worth every penny." },
    { product: "Retinol Night Repair", user: "Olivia R.", stars: 4, text: "Strong but effective, started slow and now I see real results." },
    { product: "Vitamin C Mask", user: "Hana Y.", stars: 5, text: "Brightening kicks in immediately. Love the citrus scent." },
  ],
  products: [
    { id: "PRD-1001", name: "Hydra-Glow Serum", brand: "Lumière", cat: "Serums", price: 64, stock: 142, status: "active", sku: "LUM-SER-001", emoji: "💧" },
    { id: "PRD-1002", name: "Velvet Cream Moisturizer", brand: "Aurora", cat: "Moisturizer", price: 52, stock: 88, status: "active", sku: "AUR-MOI-014", emoji: "🌸" },
    { id: "PRD-1003", name: "Vitamin C Brightening Mask", brand: "Lumière", cat: "Masks", price: 38, stock: 56, status: "active", sku: "LUM-MSK-007", emoji: "🍋" },
    { id: "PRD-1004", name: "Niacinamide 10% Booster", brand: "Pure Lab", cat: "Serums", price: 28, stock: 218, status: "active", sku: "PUR-SER-022", emoji: "🧪" },
    { id: "PRD-1005", name: "Retinol Night Repair", brand: "Aurora", cat: "Treatments", price: 72, stock: 9, status: "low", sku: "AUR-TRT-031", emoji: "🌙" },
    { id: "PRD-1006", name: "Gentle Foaming Cleanser", brand: "Lumière", cat: "Cleansers", price: 24, stock: 312, status: "active", sku: "LUM-CLN-002", emoji: "🫧" },
    { id: "PRD-1007", name: "Rose Quartz Toner", brand: "Bloom", cat: "Toners", price: 32, stock: 0, status: "out", sku: "BLO-TON-009", emoji: "🌹" },
    { id: "PRD-1008", name: "Hyaluronic Eye Cream", brand: "Aurora", cat: "Eye care", price: 48, stock: 64, status: "active", sku: "AUR-EYE-005", emoji: "👁️" },
    { id: "PRD-1009", name: "SPF 50 Mineral Sunscreen", brand: "Pure Lab", cat: "Sun care", price: 36, stock: 174, status: "active", sku: "PUR-SUN-018", emoji: "☀️" },
    { id: "PRD-1010", name: "Squalane Facial Oil", brand: "Bloom", cat: "Oils", price: 44, stock: 41, status: "draft", sku: "BLO-OIL-011", emoji: "🪔" },
    { id: "PRD-1011", name: "AHA/BHA Exfoliating Pads", brand: "Lumière", cat: "Exfoliants", price: 30, stock: 12, status: "low", sku: "LUM-EXF-003", emoji: "💎" },
    { id: "PRD-1012", name: "Peptide Lifting Serum", brand: "Aurora", cat: "Serums", price: 88, stock: 76, status: "scheduled", sku: "AUR-SER-027", emoji: "✨" },
  ],
  orders: [
    { id: "#1284", customer: "Sofia Martínez", email: "sofia@mail.com", total: 184.20, status: "paid", items: 3, date: "2026-06-27 14:14", channel: "Online", country: "ES", payment: "Visa •• 4242" },
    { id: "#1283", customer: "Liam Chen", email: "liam@mail.com", total: 62.00, status: "processing", items: 1, date: "2026-06-27 13:02", channel: "Online", country: "US", payment: "Apple Pay" },
    { id: "#1282", customer: "Amelia Brown", email: "ami@mail.com", total: 248.75, status: "paid", items: 4, date: "2026-06-27 11:48", channel: "Online", country: "UK", payment: "Mastercard" },
    { id: "#1281", customer: "Noah Patel", email: "noah@mail.com", total: 38.00, status: "pending", items: 1, date: "2026-06-27 10:33", channel: "Online", country: "IN", payment: "PayPal" },
    { id: "#1280", customer: "Hana Yoshida", email: "hana@mail.com", total: 412.50, status: "shipped", items: 6, date: "2026-06-26 16:21", channel: "Wholesale", country: "JP", payment: "Bank transfer" },
    { id: "#1279", customer: "Olivia Ross", email: "liv@mail.com", total: 96.00, status: "delivered", items: 2, date: "2026-06-26 09:11", channel: "Online", country: "AU", payment: "Visa •• 1881" },
    { id: "#1278", customer: "Mateo Silva", email: "mateo@mail.com", total: 128.40, status: "refunded", items: 2, date: "2026-06-25 18:42", channel: "Online", country: "BR", payment: "Visa •• 9210" },
    { id: "#1277", customer: "Emma Williams", email: "emma@mail.com", total: 76.00, status: "paid", items: 2, date: "2026-06-25 14:11", channel: "Online", country: "US", payment: "Apple Pay" },
    { id: "#1276", customer: "Yuki Tanaka", email: "yuki@mail.com", total: 312.00, status: "shipped", items: 5, date: "2026-06-25 09:01", channel: "Online", country: "JP", payment: "Mastercard" },
    { id: "#1275", customer: "Ava Johnson", email: "ava@mail.com", total: 54.00, status: "cancelled", items: 1, date: "2026-06-24 21:08", channel: "Online", country: "CA", payment: "Visa •• 0024" },
  ],
  customers: [
    { id: "C-1001", name: "Sofia Martínez", email: "sofia@mail.com", orders: 12, spent: 1840.20, last: "Today", segment: "VIP", country: "ES" },
    { id: "C-1002", name: "Liam Chen", email: "liam@mail.com", orders: 4, spent: 312.00, last: "Today", segment: "Loyal", country: "US" },
    { id: "C-1003", name: "Amelia Brown", email: "ami@mail.com", orders: 9, spent: 1248.75, last: "Today", segment: "VIP", country: "UK" },
    { id: "C-1004", name: "Noah Patel", email: "noah@mail.com", orders: 1, spent: 38.00, last: "Today", segment: "New", country: "IN" },
    { id: "C-1005", name: "Hana Yoshida", email: "hana@mail.com", orders: 22, spent: 4120.50, last: "Yesterday", segment: "VIP", country: "JP" },
    { id: "C-1006", name: "Olivia Ross", email: "liv@mail.com", orders: 6, spent: 596.00, last: "Yesterday", segment: "Loyal", country: "AU" },
    { id: "C-1007", name: "Mateo Silva", email: "mateo@mail.com", orders: 3, spent: 228.40, last: "2 days", segment: "Returning", country: "BR" },
    { id: "C-1008", name: "Emma Williams", email: "emma@mail.com", orders: 2, spent: 152.00, last: "2 days", segment: "Returning", country: "US" },
    { id: "C-1009", name: "Yuki Tanaka", email: "yuki@mail.com", orders: 14, spent: 2312.00, last: "2 days", segment: "VIP", country: "JP" },
    { id: "C-1010", name: "Ava Johnson", email: "ava@mail.com", orders: 1, spent: 54.00, last: "3 days", segment: "New", country: "CA" },
  ],
  categories: [
    { name: "Cleansers", products: 24, image: "🫧", parent: null },
    { name: "Toners", products: 14, image: "🌹", parent: null },
    { name: "Serums", products: 38, image: "💧", parent: null },
    { name: "Moisturizers", products: 22, image: "🌸", parent: null },
    { name: "Masks", products: 18, image: "🍋", parent: null },
    { name: "Eye Care", products: 12, image: "👁️", parent: null },
    { name: "Sun Care", products: 9, image: "☀️", parent: null },
    { name: "Treatments", products: 16, image: "🌙", parent: null },
    { name: "Oils", products: 8, image: "🪔", parent: null },
    { name: "Exfoliants", products: 11, image: "💎", parent: null },
  ],
  collections: [
    { name: "Summer Glow Edit", products: 18, status: "active", image: "☀️", schedule: "Live" },
    { name: "Sensitive Skin Routine", products: 12, status: "active", image: "🌿", schedule: "Live" },
    { name: "Night Repair Bundle", products: 8, status: "active", image: "🌙", schedule: "Live" },
    { name: "Anti-Aging Essentials", products: 14, status: "active", image: "✨", schedule: "Live" },
    { name: "Acne Care Heroes", products: 10, status: "draft", image: "🧪", schedule: "Draft" },
    { name: "Holiday Gift Sets", products: 22, status: "scheduled", image: "🎁", schedule: "Dec 1" },
  ],
  brands: [
    { name: "Lumière", products: 64, sales: "$24,820", status: "active", logo: "L", grad: "var(--grad-1)" },
    { name: "Aurora", products: 48, sales: "$18,402", status: "active", logo: "A", grad: "var(--grad-2)" },
    { name: "Pure Lab", products: 36, sales: "$12,108", status: "active", logo: "P", grad: "var(--grad-3)" },
    { name: "Bloom", products: 28, sales: "$8,920", status: "active", logo: "B", grad: "linear-gradient(135deg,#f78fcb 0%,#ffb547 100%)" },
    { name: "Botanique", products: 18, sales: "$5,210", status: "draft", logo: "Bo", grad: "linear-gradient(135deg,#1ec48b 0%,#4f8cff 100%)" },
  ],
  promos: [
    { code: "GLOW20", type: "Percentage", value: "20%", used: 482, limit: 1000, status: "active", expires: "Jul 31" },
    { code: "WELCOME10", type: "Percentage", value: "10%", used: 1248, limit: 0, status: "active", expires: "—" },
    { code: "FREESHIP", type: "Free shipping", value: "—", used: 312, limit: 500, status: "active", expires: "Aug 15" },
    { code: "SUMMER30", type: "Percentage", value: "30%", used: 94, limit: 200, status: "scheduled", expires: "Jul 1" },
    { code: "VIP50", type: "Fixed", value: "$50", used: 18, limit: 50, status: "active", expires: "Dec 31" },
    { code: "BLACKFRI", type: "Percentage", value: "40%", used: 0, limit: 1000, status: "draft", expires: "Nov 28" },
  ],
  reviews: [
    { product: "Hydra-Glow Serum", user: "Sofia M.", stars: 5, text: "Absolutely glowing skin after 2 weeks.", status: "approved", date: "Today" },
    { product: "Velvet Cream", user: "Amelia B.", stars: 5, text: "My dry skin finally feels balanced.", status: "approved", date: "Today" },
    { product: "Retinol Night Repair", user: "Olivia R.", stars: 4, text: "Strong but effective.", status: "pending", date: "Yesterday" },
    { product: "Vitamin C Mask", user: "Hana Y.", stars: 5, text: "Brightening kicks in immediately.", status: "approved", date: "Yesterday" },
    { product: "Rose Quartz Toner", user: "Mateo S.", stars: 2, text: "Didn't notice much difference.", status: "pending", date: "2 days" },
    { product: "Niacinamide Booster", user: "Liam C.", stars: 5, text: "Pore appearance reduced after 3 weeks.", status: "approved", date: "3 days" },
    { product: "Eye Cream", user: "Emma W.", stars: 1, text: "Caused irritation around my eyes.", status: "rejected", date: "4 days" },
  ],
  zones: [
    { name: "Domestic — US", countries: "United States", rates: 3, cost: "$0 – $12.50" },
    { name: "North America", countries: "Canada, Mexico", rates: 2, cost: "$8 – $18" },
    { name: "Europe", countries: "27 countries", rates: 4, cost: "€6 – €22" },
    { name: "Asia Pacific", countries: "14 countries", rates: 3, cost: "$12 – $32" },
    { name: "Rest of World", countries: "62 countries", rates: 1, cost: "$24 flat" },
  ],
  subscribers: [
    { email: "sofia@mail.com", name: "Sofia M.", segment: "VIP", joined: "Mar 2024", status: "subscribed" },
    { email: "liam@mail.com", name: "Liam C.", segment: "Customer", joined: "Apr 2024", status: "subscribed" },
    { email: "ami@mail.com", name: "Amelia B.", segment: "VIP", joined: "Jan 2024", status: "subscribed" },
    { email: "noah@mail.com", name: "Noah P.", segment: "Prospect", joined: "Jun 2024", status: "subscribed" },
    { email: "hana@mail.com", name: "Hana Y.", segment: "VIP", joined: "Feb 2024", status: "subscribed" },
    { email: "ava@mail.com", name: "Ava J.", segment: "Customer", joined: "May 2024", status: "unsubscribed" },
    { email: "yuki@mail.com", name: "Yuki T.", segment: "VIP", joined: "Dec 2023", status: "subscribed" },
  ],
  campaigns: [
    { name: "Summer Glow Launch", channel: "Email", status: "sent", recipients: 12480, opens: "42%", clicks: "8.4%", date: "Jun 14" },
    { name: "Welcome Series — Day 1", channel: "Email", status: "active", recipients: 1248, opens: "58%", clicks: "12.1%", date: "Ongoing" },
    { name: "Retinol Education", channel: "Email", status: "draft", recipients: 0, opens: "—", clicks: "—", date: "—" },
    { name: "Cart Abandoned 24h", channel: "Email", status: "active", recipients: 412, opens: "48%", clicks: "9.2%", date: "Ongoing" },
    { name: "VIP Early Access", channel: "SMS", status: "scheduled", recipients: 842, opens: "—", clicks: "—", date: "Jul 1" },
  ],
  pages: [
    { title: "About Us", slug: "/about", status: "published", updated: "Jun 18" },
    { title: "Our Ingredients", slug: "/ingredients", status: "published", updated: "Jun 12" },
    { title: "Sustainability", slug: "/sustainability", status: "published", updated: "May 28" },
    { title: "FAQ", slug: "/faq", status: "published", updated: "May 20" },
    { title: "Shipping & Returns", slug: "/shipping", status: "published", updated: "Apr 14" },
    { title: "Privacy Policy", slug: "/privacy", status: "published", updated: "Apr 02" },
    { title: "Press Kit 2026", slug: "/press", status: "draft", updated: "Jun 22" },
  ],
  posts: [
    { title: "The Glow Guide: Building a Morning Routine", author: "Aria Mendez", status: "published", date: "Jun 22", views: 4820 },
    { title: "Niacinamide 101: What It Actually Does", author: "Dr. Lena Park", status: "published", date: "Jun 14", views: 6210 },
    { title: "Why Your Sunscreen Choice Matters in 2026", author: "Aria Mendez", status: "published", date: "Jun 02", views: 8120 },
    { title: "Retinol Without the Irritation", author: "Dr. Lena Park", status: "draft", date: "—", views: 0 },
    { title: "Inside Our Lab: Formulating Hydra-Glow", author: "Aria Mendez", status: "scheduled", date: "Jul 02", views: 0 },
  ],
  media: [
    { name: "hydra-glow-hero.jpg", size: "1.2 MB", type: "jpg", emoji: "🖼️", date: "Jun 14" },
    { name: "velvet-cream-pdp.jpg", size: "892 KB", type: "jpg", emoji: "🖼️", date: "Jun 14" },
    { name: "lab-process-1.mp4", size: "8.4 MB", type: "mp4", emoji: "🎬", date: "Jun 12" },
    { name: "ingredients-list.pdf", size: "240 KB", type: "pdf", emoji: "📄", date: "Jun 10" },
    { name: "summer-edit-banner.png", size: "1.8 MB", type: "png", emoji: "🖼️", date: "Jun 08" },
    { name: "founder-portrait.jpg", size: "1.1 MB", type: "jpg", emoji: "🖼️", date: "Jun 05" },
    { name: "packaging-mockup.png", size: "2.1 MB", type: "png", emoji: "🖼️", date: "Jun 01" },
    { name: "routine-flow.svg", size: "32 KB", type: "svg", emoji: "🎨", date: "May 28" },
    { name: "ad-creative-fb.jpg", size: "780 KB", type: "jpg", emoji: "🖼️", date: "May 24" },
    { name: "ad-creative-ig.jpg", size: "812 KB", type: "jpg", emoji: "🖼️", date: "May 24" },
    { name: "press-release.docx", size: "84 KB", type: "doc", emoji: "📄", date: "May 18" },
    { name: "logo-mark.svg", size: "12 KB", type: "svg", emoji: "🎨", date: "May 02" },
  ],
  team: [
    { name: "Aria Mendez", email: "aria@lumiere.shop", role: "Owner", lastActive: "Now", avatar: "AM" },
    { name: "Jules Park", email: "jules@lumiere.shop", role: "Admin", lastActive: "2h ago", avatar: "JP" },
    { name: "Mira Singh", email: "mira@lumiere.shop", role: "Manager", lastActive: "Today", avatar: "MS" },
    { name: "Theo Ng", email: "theo@lumiere.shop", role: "Staff", lastActive: "Yesterday", avatar: "TN" },
    { name: "Iris Costa", email: "iris@lumiere.shop", role: "Staff", lastActive: "3 days", avatar: "IC" },
  ],
  notifications: [
    { type: "order", title: "New order #1284", body: "Sofia Martínez — $184.20", time: "2m ago", unread: true },
    { type: "stock", title: "Low stock alert", body: "Retinol Night Repair · 9 units left", time: "18m ago", unread: true },
    { type: "review", title: "New 5★ review", body: "Hydra-Glow Serum · Sofia M.", time: "1h ago", unread: true },
    { type: "order", title: "Refund processed", body: "#1278 — $128.40 refunded to Mateo Silva", time: "3h ago", unread: false },
    { type: "campaign", title: "Campaign sent", body: "Summer Glow Launch reached 12,480 inboxes", time: "Yesterday", unread: false },
    { type: "system", title: "Backup completed", body: "Daily catalog backup completed successfully", time: "Yesterday", unread: false },
  ],
  homepageSections: [
    { type: "Hero", title: "Glow that lasts", subtitle: "Summer Edit 2026", visible: true },
    { type: "Featured Collection", title: "Summer Glow Edit", subtitle: "18 products", visible: true },
    { type: "USP Bar", title: "Free shipping · 30-day returns · Cruelty-free", subtitle: "—", visible: true },
    { type: "Editorial", title: "The Routine Builder", subtitle: "Interactive quiz", visible: true },
    { type: "Bestsellers", title: "Loved by 12K+", subtitle: "Top 8 products", visible: true },
    { type: "Testimonials", title: "5-star reviews", subtitle: "Auto-pulled from Reviews", visible: true },
    { type: "Newsletter", title: "Join the Glow Letter", subtitle: "Footer CTA", visible: false },
  ],
  navMenus: [
    { area: "Header — Main", items: ["Shop", "Routines", "Ingredients", "Journal", "About"] },
    { area: "Header — Shop dropdown", items: ["Serums", "Moisturizers", "Cleansers", "Masks", "Sun Care", "Eye Care", "Treatments"] },
    { area: "Footer — Company", items: ["About", "Sustainability", "Press", "Careers", "Contact"] },
    { area: "Footer — Help", items: ["Shipping", "Returns", "FAQ", "Track Order", "Privacy"] },
  ],
};
